// Code generated by 'go generate'; DO NOT EDIT.

package w32api

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")

	procFindClose        = modkernel32.NewProc("FindClose")
	procFindFirstStreamW = modkernel32.NewProc("FindFirstStreamW")
	procFindNextStreamW  = modkernel32.NewProc("FindNextStreamW")
)

func findClose(findFile windows.Handle) (err error) {
	r1, _, e1 := syscall.Syscall(procFindClose.Addr(), 1, uintptr(findFile), 0, 0)
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func findFirstStream(fileName *uint16, infoLevel int32, findStreamData unsafe.Pointer, flags uint32) (hnd windows.Handle) {
	r0, _, _ := syscall.Syscall6(procFindFirstStreamW.Addr(), 4, uintptr(unsafe.Pointer(fileName)), uintptr(infoLevel), uintptr(findStreamData), uintptr(flags), 0, 0)
	hnd = windows.Handle(r0)
	return
}

func findNextStream(findStream windows.Handle, findStreamData unsafe.Pointer) (err error) {
	r1, _, e1 := syscall.Syscall(procFindNextStreamW.Addr(), 2, uintptr(findStream), uintptr(findStreamData), 0)
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}
